[server]
headless = true
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"
port = 5000

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#00ffff"
backgroundColor = "#000000"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#00ff00"